services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/websec/src
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db/badbank
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=badbank
    ports:
      - "5432:5432"

volumes:
  postgres_data: